== HiveMQ Homebrew Repository

This repository contains link:http://brew.sh/[Homebrew] Formulas for installing HiveMQ and HiveMQ related plugins and tools for MacOSX.

=== Requirements

To make use of the link:http://brew.sh/[Homebrew] Formulas, you first have to install Homebrew on your OSX.

The next step is to tap the Homebrew HiveMQ repository:

[source,bash]
.Tapping the repository
----
brew tap hivemq/homebrew-hivemq
----

=== Installing HiveMQ and plugins

After tapping the repository, it's trivial to install HiveMQ and its plugins:

==== HiveMQ

[source,bash]
.Installing HiveMQ
----
brew install hivemq
----


==== HiveMQ Message Log Plugin

[source,bash]
.Installing the MQTT Message Log Plugin
----
brew install hivemq-mqtt-message-log
----

==== HiveMQ Access Log Plugin

[source,bash]
.Installing the MQTT Access Log Plugin
----
brew install hivemq-mqtt-accesslog
----


==== HiveMQ Deny Root Wildcard Subscriptions Plugin

[source,bash]
.Installing the Deny Root Wildcard Subscription Plugin
----
brew install hivemq-deny-root-wildcard-subscriptions
----



==== HiveMQ File Authentication Plugin

[source,bash]
.Installing the File Authentication Plugin
----
brew install hivemq-file-authentication
----


==== HiveMQ Stormpath Plugin

[source,bash]
.Installing the Stormpath Plugin
----
brew install hivemq-stormpath
----


